### ISSUE TITLE
FormDataMultiPart class gets generated in target/java-gen. Related to #105

### ISSUE THREAD

**Issue by sumveds** [mulesoft/raml-for-jax-rs#119]
Hi,

Using approach mentioned in #105, the ```FormDataMultiPart``` is getting generated in the ``target/java-gen``` folder. The class looks like below:
```

package org.glassfish.jersey.media.multipart;

public class FormDataMultiPart {

}

```

I do not want to get this generated as I am going to use jersey ```org.glassfish.jersey.media.multipart.FormDataMultiPart``` class.

Regards,
Sumved

**Comment by KonstantinSviridov** [comment]
Hi @sumveds 

Thanks again for reporting an issue.

First, we must not generate a DTO for `multipart/formdata` content type.
Second, we should provide possibility to cancel DTO generation for particular method.

I'll switch to it in the nearest future.

Regards,
Konstantin

**Comment by KonstantinSviridov** [comment]
Ok, in order to use existing class rather then generate a new one, your `onAddResourceMethod` method must be like this:
```
	public void onAddResourceMethod(
			JMethod method,
			Action action,
			MimeType bodyMimeType,
			Collection<MimeType> uniqueResponseMimeTypes) {
		List<JVar> params = method.params();
		if(params!=null&&!params.isEmpty()){
			for(JVar param : params){
				JType paramType = param.type();
				if(paramType!=null&&paramType.fullName().equals("javax.mail.internet.MimeMultipart")){
					JClass clazz = codeModel.ref("com.sun.jersey.multipart.FormDataMultiPart");
					param.type(clazz);
				}
		}
	}
```

It appers that the `com.sun.codemodel.JCodeModel` method determines whether a new class is generated or not. `_class(String)` forces generation while `parseType(String)`, `ref(String)`, `ref(Class<?>)` and `_ref(Class<?>)` do not.

I will edit my comment in #105 in order to make it a proper example.

Regards, Konstantin.
