### ISSUE TITLE
When will a release build be available?

### ISSUE THREAD

**Issue by pmbober** [mulesoft/raml-for-jax-rs#23]
When will a release (non-snapshot) version of this project and (and the associated raml-java-parser) be available?

**Comment by talios** [comment]
Happy New Year RAML-JAXRSers! Hope you all had a great Christmas/break - now that the new years kicking off I was wondering if there was any progress on getting either public SNAPSHOTs or a release available?

**Comment by petrochenko-pavel-a** [comment]
Hi Talios, all thanks a lot for your congratulations, I have added a links to snapshot builds to documentation if their will be ok for most o f users we will promote them to release.

P.S. Any feedback to snapshots is very appreciated


Thanks in advance,
Pavel

**Comment by ddossot** [comment]
+1 on a release please, everyone has to run their fake "RC" releases in their own repos so they can release their own projects (can't have a plug-in in SNAPSHOT when you release). Don't wait for these tools to be "done" before releasing them because they'll never be done...

It doesn't need to be on released on Central, it can be in MuleSoft's Nexus if it makes things easier. Any release would also re-assure us of MuleSoft's committment to these tools...

Also please use a version number that's related to the RAML version, for ex. `0.8.0` for the first release.

**Comment by talios** [comment]
@petrochenko-pavel-a I don't see any links to a SNAPSHOT maven repository added? Only links to the command line version?

**Comment by amr** [comment]
+1 for releases. This is what Spring does, they provide snapshots but they provide releases of their development milestones. So that early adopters can use those releases as soon as they can. I use such releases just fine in my production builds as they are *predictable*.

**Comment by scottfromsf** [comment]
+1, looking forward to this being on Maven Central.

**Comment by petrochenko-pavel-a** [comment]
Hi Guys we established publishing to https://repository-master.mulesoft.org/ please let me know if it is not enough for your needs.

Regards,
Pavel

**Comment by ddossot** [comment]
This ticket is about releasing the plugins, not just snapshot builds.

At this point, there's still no release of these plugins in the MuleSoft public releases repo: https://repository.mulesoft.org/nexus/content/repositories/releases/org/raml/

Without official releases from MuleSoft, everyone is forced to build their own non-snapshot releases in order to be able to release their own projects which depend on these plugins.

The current version is `1.3.2-SNAPSHOT`, suggesting that many releases have occurred but where are they? Could you release `1.3.2`?

**Comment by ddossot** [comment]
I can't re-open this issue so I've opened a new one: https://github.com/mulesoft/raml-for-jax-rs/issues/37

**Comment by usarid** [comment]
Reopening

**Comment by ddossot** [comment]
Thanks! I'll close the other one then.

**Comment by petrochenko-pavel-a** [comment]
Ok, I am deploying to releases repository right now

**Comment by petrochenko-pavel-a** [comment]
Hi ddosot, please check if you are able to see a release at https://repository-master.mulesoft.org/nexus/content/repositories/releases/org/raml/

(it works fine for me now)

Thanks in advance,
Pavel

**Comment by ddossot** [comment]
Yes, it works! :dancer: 

I see the repository is `repository-master.mulesoft.org` instead of the usual `repository.mulesoft.org`. Is `repository.mulesoft.org` being replaced by `repository-master.mulesoft.org`?

**Comment by petrochenko-pavel-a** [comment]
I do not know actually this is the repo, to which I have access and which was provided to me by the guys. I may/will ping them but collaboration with CI guys is very slow

Regards,
Pavel

**Comment by petrochenko-pavel-a** [comment]
P.S. and I guess it is better then nothing.
Please let me know if I may close issue now. (sorry I was not aware that you can not reopen it)

**Comment by ddossot** [comment]
I'm personally happy with this release and this repo. It's closeable AFAIAC.

**Comment by ddossot** [comment]
Precision here: I think `repository.mulesoft.org` is a mirror of `repository-master.mulesoft.org` and I think it is the one to use for external users.

Indeed, I've added this to my `pom`:

        <pluginRepository>
            <id>ms.releases</id>
            <url>https://repository.mulesoft.org/nexus/content/repositories/releases/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </pluginRepository>

and now the release has [appeared in the mirror](https://repository.mulesoft.org/nexus/content/repositories/releases/org/raml/plugins/raml-jaxrs-maven-plugin/)!

**Comment by ddossot** [comment]
Well, this :arrow_up: is kind of moot since #34 has been re-opened and releases will eventually make their way to Maven Central. Let's say it's an "in the meantime" fix :smile_cat:
