### ISSUE TITLE
Need a way to customize the generated function names

### ISSUE THREAD

**Issue by andreschembri** [mulesoft/raml-for-jax-rs#78]
Hi , 

I am currently generating the JAX-RS code using a raml file, it seems that the function name is generated using the following {http-verb}{1stResource}{2ndResource}{nthResource}. 

The issue I am having is that the function name is getting massively long because the paths are very long. 

Initially I was assuming that if the displayName is changed the generator would use these. but this is not the case. 

After a quick discussion it was suggested to me to open a ticket here suggesting some kind of extension to map the function names to the resource calls (perhaps through a properties file).

**Comment by ddossot** [comment]
That's an excellent point.

Supporting multiple naming strategies would be great. We could have the current "verb and resource path" as the default (in order to be backwards compatible) and offer extra strategies, like "display names" or "paths to names in properties".

Considering the display name approach and your personal use case, what would be a nice strategy? Concatenating the HTTP verb and the display name? Something else? Your insight on this, with some examples, would help a lot.

**Comment by andreschembri** [comment]
Hi David, 

Thanks for your reply. 

For my particular use case display names are good enough, however there is a specific drawback with this implementation, that is that display names do not guarantee unique names, furthermore when a RAML file is passed to a client it might have display names that are not meaningful from a java perceptive, although one might argue that in that case the api designer might not be choosing the correct display names . 

However with the mapping approach it might mean that the RAML file would not be the "single source of truth" anymore.

Another approach might be to have a specific attribute for code generation in the RAML file itself. 

However personally I would say that the displayName if defined correctly should represent the actual name that a function should have.

**Comment by ddossot** [comment]
We can Java-ify display names. Making sure these names are unique would be a task left to the RAML author, which would not be asking too much IMO. Altough the spec (righteously) says nothing about unique display names, in the case of generating code from RAML, it's acceptable to require them to be unique.

@petrochenko-pavel-a Any thoughts on this discussion?

**Comment by KonstantinSviridov** [comment]
Hi, @andreschembri and @ddossot 

We have just implemented an extension which composes method names. Unfortunately, it appeared that `org.raml.model.Action` class (which is method model utilized by the RAML parser) does not have a `displayName` field. Thus, we can not implement desired way of method naming until the
https://github.com/raml-org/raml-java-parser/issues/67
is resolved.

The implemented extension compose names like
```
methodType + resource displayName
```

After the method `displayName` issue is resolved, it will be easy to implement desired naming way.

The extension class is `org.raml.jaxrs.codegen.core.ext.ResourceDisplayNameBasedMethodNameBuilder`.

In order to enable it, you should place it into configuration inside `pom.xml`:
```
<configuration>
	<sourceDirectory>${basedir}/raml</sourceDirectory>
	<outputDirectory>${basedir}/src/main/java</outputDirectory>
	<basePackageName>org.raml.jaxrs.example</basePackageName>
	<jaxrsVersion>2.0</jaxrsVersion>
	<useJsr303Annotations>false</useJsr303Annotations>
	<jsonMapper>jackson1</jsonMapper>
	<removeOldOutput>true</removeOldOutput>
	<extensions>
		<extension>org.raml.jaxrs.codegen.core.ext.ResourceDisplayNameBasedMethodNameBuilder</extension>
	</extensions>
</configuration>
```

Regards,
Konstantin

**Comment by ddossot** [comment]
:+1: cool stuff!

**Comment by sahilsobti** [comment]
@KonstantinSviridov  Can you provide more details on how to use this extension class for having better interface and class names?
