### ISSUE TITLE
validating json

### ISSUE THREAD

**Issue by rajkumar1979** [mulesoft/raml-for-jax-rs#85]
Hi,

I am using the raml to jaxrs plugin and I am successfully able to generate the java code, I am trying to test the rest API for invalid json,

When I try to enter an invalid json I get an error response saying
Unrecognized field "accountDetail" (Class com.intuit.platform.webs.subscription.model.SubscriptionRequest), not marked as ignorable at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@35bb12d0; line: 2, column: 61] (through reference chain: com.intuit.platform.webs.subscription.model.SubscriptionRequest["accountDetail"])

the logs dont show any exceptions.

The goal is to catch this exception and provide a meaningful error response.

**Comment by rajkumar1979** [comment]
I tried writing an exception mapper but then it get never gets invoked.

**Comment by ddossot** [comment]
This is a runtime issue and, as such, doesn't seem related to the RAML-to-JAX-RS generator (which is not used at runtime) but to some configuration issue in Jersey and/or the JSON serializer you are using.

If you use plain resources and POJOs not generated by RAML-to-JAX-RS do you get the same issue? If not, what's the difference?

But if yes, I think this question should be asked to a Jersey discussion group instead.

**Comment by KonstantinSviridov** [comment]
Hi, @rajkumar1979 

Your exception seems to be thrown by Jersy before the generator produced code starts executing. Thus, we can not modify the produced code to handle it.

If you still have a feeling that the generator produced code is responsible for the exception, please, reopen the issue and provide an example so that we could investigate it.

Regards, Konstantin.
