### ISSUE TITLE
Is @XmlRootElement even needed for json?

### ISSUE THREAD

**Issue by ymajoros** [mulesoft/raml-for-jax-rs#88]
Resteasy/Jackson work fine without it.

Just wondering, is there any added value to even check it?

**Comment by KonstantinSviridov** [comment]
Hi, @ymajoros!

It is not needed for JSON.

Regards, Konstantin.

**Comment by ymajoros** [comment]
Hi @KonstantinSviridov,

Why is it needed? My web services don't need it, it works well without. Why would json schema generation need that?

Regards, Yannick

**Comment by KonstantinSviridov** [comment]
Hi, @ymajoros 

In fact, I wrote that it is NOT needed, but I was misstaken. I was looking on generation results for classes which occur as @ApiOperation.response values, and for them it is indeed not needed.

But the situation is different with classes which occur just as method return values. For them we really require @XmlElement.

The reason is that we want the user to directly point the classes, he whishes to use as generation input. And setting the @XmlElement is the way to do it.

You may want some setting which prevents the generator from inspecting @XmlElement and makes it work in any case. If so, please, create another issue for it.

Regards, Konstantin.

**Comment by ymajoros** [comment]
I'm talking about @XmlRootElement, not @XmlElement. Currently, the former is required to generated a schema for entities. I think this isn't necessary.

**Comment by KonstantinSviridov** [comment]
@ymajoros 
I am also talking about @XmlRootElement
It's a misstake in the previous message. Sorry.
